# Generated by Django 5.2.7 on 2026-06-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+1 (234) 567-890', max_length=50)),
                ('email', models.EmailField(default='info@muslimahabayas.com', max_length=254)),
                ('opening_hours_weekdays', models.CharField(default='Monday - Friday: 9:00 AM - 6:00 PM', max_length=100)),
                ('opening_hours_sat', models.CharField(default='Saturday: 10:00 AM - 4:00 PM', max_length=100)),
                ('opening_hours_sun', models.CharField(default='Sunday: Closed', max_length=100)),
                ('instagram', models.URLField(default='https://instagram.com', max_length=300)),
                ('facebook', models.URLField(default='https://facebook.com', max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.RemoveField(
            model_name='abaya',
            name='price',
        ),
    ]
