# Generated by Django 5.2.7 on 2026-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactinfo_remove_abaya_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_handle',
            field=models.CharField(default='Muslimah-Abayas', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_handle',
            field=models.CharField(default='_muslimahabayas_', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default='+91-9917041149', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='shopmuslimahabayas@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(default='https://facebook.com/Muslimah-Abayas', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(default='https://instagram.com/_muslimahabayas_', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+91-9917041149', max_length=50),
        ),
    ]
